---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1mqnqku2r3egl6r0yg7qckwvmc5gzj3kjq4tvvqg53flg3m92necqr9u5tf"
  - path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1mqnqku2r3egl6r0yg7qckwvmc5gzj3kjq4tvvqg53flg3m92necqr9u5tf"
