---
apiVersion: v1
kind: ConfigMap
metadata:
  # These values will be available to all YAML resources as ${VARIABLE_NAME}.
  name: cluster-settings
data:
  # Configuration
  CONFIG_TIMEZONE: "Europe/Stockholm"
  CONFIG_APP_UID: '"5000"'
  CONFIG_APP_GID: '"5000"'
  CONFIG_APP_USER: "k8s"
  CONFIG_APP_GROUP: "appdata"
  # K8s Cluster
  CLUSTER_NAME: "k8s-dev"
  CLUSTER_POD_CIDR: "10.69.0.0/16"
  CLUSTER_SVC_CIDR: "10.96.0.0/16"
  # K8s Cluster Storage
  CLUSTER_STORAGE_BLOCK: "truenas-ssd-iscsi"
  CLUSTER_SNAPSHOT_BLOCK: "truenas-ssd-iscsi"
  CLUSTER_STORAGE_NFS: "truenas-ssd-nfs"
  CLUSTER_SNAPSHOT_NFS: "truenas-ssd-nfs"
  CLUSTER_STORAGE_HOSTPATH: "openebs-hostpath"
  CLUSTER_SNAPSHOT_HOSTPATH: "openebs-hostpath"
  # Networks
  NET_LOCAL_CIDR: "192.168.20.0/24"
  NET_L2POOL_CIDR: "192.168.20.32/27"
  NET_STORAGE_CIDR: "10.0.100.0/24"
  NET_WHITELIST_IP_RANGES: "192.168.20.0/24, 192.168.30.15/32"
  # Services
  SVC_NGINX_INTERNAL_IP: "192.168.20.80"
  # Service Ports
