apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:3c6+R/VkFfrTJSPaavFhSaJfqUwUfR7kBRcuLQIuXP3v5Lb0feaBVfbNNdU88mG12gpBa78pCqMm2+VG17mbqsmhOJJ8dZttlL3q2dghX0JLuSPxMtt85MyywOWU7xYvdkqQEBvSDA8o/f2SwIA6THNEl5zLKZpbiTdV1BXM6GuNzKBC8j3lYL/xwaIA3FDzrCAKTp4sMg8=,iv:4KukhavLTXbZx5lQuVTBvxQJYyv5rXzvYPMdpR2oYx0=,tag:hD/kf7OfnWL9nHLp09WNUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16jrnvsqz55me3ju4kl96y2tjs90gygyvk5ren7ch8mv2rxtrqvus508fpn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa3FmVmRYeFB2dVNwWEpL
            OHpuZWhiTEFxcE1yZ1VmV083RlpEUmdjMkNRCll3bkp2V2w0SFpVMFBlbGpnQVN2
            c0tyWHBxdVBvaG1OTHdEMzhaMElrTkUKLS0tIG1kTWNWVkdSR3hsRk5RL09tMFFH
            ZVBIWnJrR0Z0ZFdGOXJLZ1J1YWpFdjgKFCSVcHAoM7Vn84qYz6tC8NJfSZ3m2cYU
            yVmztwwj9yZoHmPjYgIp7ick7dco6Cu3wiL4sC8ebFIZikzxvbzJ9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T13:20:17Z"
    mac: ENC[AES256_GCM,data:tagvB8Ob5FyZLno0Nl13ItzAUkMaLRBGGittuIEbhZRznmQcbjx0AN2gWN7DQ+ugBrUJpS/cByz4lNd2/1aofsE5JVcJI4qDuUiSNYmCeAR/i18rIUoYd+oG75T0GhnRh1yFWYFrpIlJ962a++PCtFg28CgG2EeSRkqhoIF+F70=,iv:uTGOsVwlkUKVzU2+81zTsSWwyshnnwib06ftv45Wr2A=,tag:wrDVSkm97ftzPEqZVghyNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.1
