---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cluster-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        # Cloudflare
        SECRET_CLOUDFLARE_TUNNEL_ID: "{{ .CLOUDFLARE_DEV_TUNNEL_ID }}"
        # Domains
        SECRET_DOMAIN: "{{ .PRIVATE_DOMAIN }}"
        # SMTP
        SECRET_EMAIL: "{{ .ADMIN_EMAIL }}"
        # TrueNAS
        SECRET_NAS_IP: "{{ .TRUENAS_IP }}"
        SECRET_NFS_PATH_IMMICH: "{{ .NFS_PATH_IMMICH }}"
        SECRET_NFS_PATH_MEDIA: "{{ .NFS_PATH_MEDIA }}"
        SECRET_NFS_PATH_MINIO: "{{ .NFS_PATH_DEV_MINIO }}"
        SECRET_NFS_PATH_MUSIC: "{{ .NFS_PATH_MUSIC }}"
        SECRET_NFS_PATH_PGBACKUPS: "{{ .NFS_PATH_PGBACKUPS }}"
        SECRET_NFS_PATH_PHOTOS: "{{ .NFS_PATH_PHOTOS }}"
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: domains
    - extract:
        key: truenas
