---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/alerts
  - ../../components/global-vars
  - ../../components/namespace
  - ../../components/sops
resources:
  # Flux-Kustomizations
  - ./kube-prometheus-stack/ks.yaml
  - ./kubernetes-dashboard/ks.yaml

