apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1/3IoPtZgP4o1Ppc,iv:Dr0JllUFwQ1kMRjk4/a75MYnh+ex+PdGPVMShx1/YGE=,tag:W7CArOaY3JkfkJszP2CXIQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:Jq+lt2hz3S8s4w6a/w==,iv:pWu/f+YzfExeJOwdwEDqH7cVQGMey2YCEGjsl5jdP7A=,tag:2yJ+olZfbmhd3gWCP0FKIA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KZFFAAChobp7NcejoU5UtsMRaLtN16GXcMHFA0RUZxvLYyT7,iv:KVSwVkiBHvHTu1tdfYO7IQ0r+v9JgXXgTM/E/LXaMa8=,tag:vEBuP5tdtOMUjlosGBf13Q==,type:str]
    SECRET_NAS_IP: ENC[AES256_GCM,data:+PAJZEUwpRFkbw==,iv:mNDF83BMECNjTf8wookugTnzTtjd1mm26NfiqvJRXRA=,tag:2/vgZFxTuTLGXSnWG9AnsA==,type:str]
    SECRET_NFS_PATH_IMMICH: ENC[AES256_GCM,data:QewSHf6WVUTzSO7qWUejASK+Xto=,iv:pcsdyFonRP86U4eu154v1Gtp1DT+bkZt5Sq+7THESDo=,tag:c5orL39t+UkpUimS8KYnHw==,type:str]
    SECRET_NFS_PATH_MEDIA: ENC[AES256_GCM,data:6DpYZaP+oGnLJhc4JDYRZLANj/U=,iv:9t8xOX/H1buVxN5RZHOzsJ3ozoU5zEqctcuJV8aCEwc=,tag:fb0aWiztfTdDRZQMOKCxCQ==,type:str]
    SECRET_NFS_PATH_MUSIC: ENC[AES256_GCM,data:Jw7w4AtONt7QqFVBM3reRmovcbyImGPs3BYdKlGU+Fp/dA==,iv:oWzLKedL4bfQ+dQD5FlWbJEokgZYSA6zaXhamPSaFD0=,tag:Stl5tdZdhmwM8DqAu7xp6w==,type:str]
    SECRET_NFS_PATH_PGBACKUPS: ENC[AES256_GCM,data:orBULEkz+3a8sO1BeKatFiqEjvKsBpYku/GZRjGOGqc=,iv:HOfkWcWkgLYUXvJMphCD49xghAtobdIoFZTJQ3eX6z0=,tag:neLzBtb+8htcyQ7Y/M2+Sw==,type:str]
    SECRET_NFS_PATH_PHOTOS: ENC[AES256_GCM,data:3DdspgSFHCHG6IJdh3NCdsuY2NA=,iv:AGTLs/WOM1ezEDLC9vGClL71Fd19hzU6C4ScS6Rlr2U=,tag:jfjzyhT8oO406Zmm8LBI8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqnqku2r3egl6r0yg7qckwvmc5gzj3kjq4tvvqg53flg3m92necqr9u5tf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Qy85dlRMa0M2YityRWVa
            WVdXZ2Q0elV1V3U3TGhRY2x0VEh5NVE3YVJZCm9qRG5CL2RxY3dUQ2U5RmNOSzhr
            WUVIWVlhUUpGVWl3a0FCc0tRaW5oSGcKLS0tIEdZSGtWNDR3cWNaa0dOamd2NkMy
            UEMyYkF2SVR1c05ZOE96WUpreUNnblUKOq8L+DdYcFXwNGFq51ajzSOpgWyg7wJz
            7449gAoi7bxHIUeCkgx75NsNvWlDC7B3NfhmSB0/QXO3i3zF1WgjtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T22:37:36Z"
    mac: ENC[AES256_GCM,data:UmGvVfHnxZftlxVuE/ecgoaeTtR/ScbvrpqPkQdah6z6mraPJmlyubfodEe1b1wwNHSv7GOeo/+ATf1FkPA5bqaM4HJzgChbZOnAqZp0dUOPA5ygeNOITRfloZ/U6ViDwjb+D2DXai52HrkPvBFI3R4hB5oWmySqv1RgrJtFwMQ=,iv:gl6Cv153r+hvHKR4bTJlMg+g2E/x/SGrTCogGreWbY0=,tag:n/NK3jiySvXbZZ1dHUL6ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
