apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Y4OjoUhhUe7/him5,iv:pssTFZxeP37Sikb7ltgAe+rPgkm15/TwEBRvxGGGuJ4=,tag:tyK83czuS7ief0jANjaXbg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:2mPSp0VuycyRKqK3/Q==,iv:Xx3wtIYVqHzCvT0I6FBIudLWJuvxh9vCVIvy57cW9tE=,tag:a4Syf7FqexwVHJoLM4tWhA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NdcDxaae1HaFkoHYA1hhyjlFXF8OdiZQt1lstOWq1aadM6iR,iv:xU1Fl7HRRXuV4NsdBDxyjKXrtIj4lLszs8vYrUs60Z8=,tag:UgZ/HS0QZ+b8P7a/xqsx+A==,type:str]
    SECRET_NAS_IP: ENC[AES256_GCM,data:vdBOH4trwlGFvQ==,iv:Clqh4nC13uSkuy6EWG3PDtXcSXj+dk7xSmdoAHbSboI=,tag:1aEnx/36rRbgGtrn7r1OuA==,type:str]
    SECRET_NFS_PATH_IMMICH: ENC[AES256_GCM,data:9ytlmmF0uVlvDTNDyxdDXI6259M=,iv:gDNtPqUNHpy+XtX6Yj/oDJR/vtxNCPKcaVvEosjnsNs=,tag:X75ccGqHWp3RRiw+Gb4nNw==,type:str]
    SECRET_NFS_PATH_MEDIA: ENC[AES256_GCM,data:+olMht3UjsP/3wDc/qBNegtDBmE=,iv:lpPo6O/7p+fVw9EA6R2wfQdNXQLdjo6eobGuQolybPY=,tag:UTA7qJ0XfS623+UpWehz7Q==,type:str]
    SECRET_NFS_PATH_MUSIC: ENC[AES256_GCM,data:5alAsDboBwcfsIaYs2FdQnB9F85P9TG0euSOeOaIwW6YxA==,iv:8dHpXhtXLzHrJyPBHw116zdFAPkXigBs5B9ccHtSuEQ=,tag:J0/6obXc+MO5kaw7fPsKfw==,type:str]
    SECRET_NFS_PATH_PGBACKUPS: ENC[AES256_GCM,data:jBb9dAF2JKc8DTcf2mEmg6LuD+L9Ircvr0kERe0aZfI=,iv:rFktt9kR47ZKzQMi6Xo+A6Rn/GZ+B0PZKwvDE6RH1h8=,tag:FZPQbESdu9kH/CdV5KB+Fw==,type:str]
    SECRET_NFS_PATH_PHOTOS: ENC[AES256_GCM,data:70cGZROweUHq5VGN7JJZqMUBq2U=,iv:Jxunhk3BLR2QyetiTXC1BGwSMXyZwT5KO4ZVcplBoG0=,tag:UIfN89bkXSqf9dYw1SUg1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6dwex7sla2rylxu4346z758najcz5xpp3drtk0rcm3g0pskk95sf09wu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSemo1VEdVZGdETHduV3hm
            c2l4bnFYUUhuZW9waEp2QzFkcFNXZHFlNTJrCjd5ZG84OHc0amZHYWd2eVVyOXFn
            cU5GTkt1Uzdlc25uNEVTczV5dXMrWVEKLS0tIHRQc2k3dlNkUndKR0w4NlBZMVRN
            SC83bDd6ZVQ2dWZlWHorSVpVTHJjUm8K3o1rTWmyVnBSOM7xBwWTRsSzWjzgcbeB
            msttTb3dKjvD/zXPy6Jqh0f8+CX6Tc3NrYEOVvxsZ3QBvOGNWB17/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T22:00:46Z"
    mac: ENC[AES256_GCM,data:v23jtJ4Axaee23mo4CzV4F8XigPCbcWhrjqjt8Rn6i9d/S7uh9JVctxRjYr0yGc4KA/xGe2laU+r93wBEQ0AiTNPi6x4uELqxS73oTXA7nioBzjYdNwhFBWy7tfPrECfFZV+BS08ZnNGdAmq4lm9sXufM2fwpCr9k8YOB8b9r8g=,iv:KgwNzzXD9oyvIdq9J5fNZX3m1AEEc1cVynuKpPXIyQQ=,tag:TP+Tct5JbHQpGsk07fUnOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
