apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:pbz/wgAsjOh0hu6Y,iv:sDGu8fPHgVNYU0niA4JPG12d+3hdevtCmXMVLx/fiKw=,tag:6MSkZh+C5xLwCIk+8EZpzQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:rYZ/pANJB0T8AbEubg==,iv:MBy0iVFoZTWryEvV89dCia1GCSnOL4pcPIgXNzWGkXI=,tag:EClIoPUUX1lDgOn7ZV1mgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15khkarcjpjay5hl2jv5t8x7hnycrwqa5f2h04fksvwkllxnqw3dsaxrfm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU0twSUE4blBsNHNtNmlL
            MjZXVWFnWngzZm42cExBbFkwbExuTFlodnpZCldlVFY4RWxjTHZkcWZPU1NldzY1
            N0dvZzZwUFdCUklvSmw0dWRwVll4Z1kKLS0tIGkzeUhsWFQya09JVmo4NHlWWkxQ
            a0ZXQXVqdU1jQUNKQVVoMjZ4TkxaU3MKF3IiwqLYYZlxSqcWhsFqRgaFqpWsqWz7
            cY0YJ9Fade6G3uxh4lAoUpuQ6JdSi11sF6dmlyUGF4NSmbwNNcp5AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T12:24:58Z"
    mac: ENC[AES256_GCM,data:rjdpqE1nY7mJCtayCOWH2vyay1QrGVuIIGq9NxS0mJu9IUre9iLMLc0pjbPO/7hOjomF/4/WeBeY70Gat2bgwUm6o2m/bDt/eLRd6u/IywXiwU+SRD64SIVFUM0gA7L4lu6DeoTu+Qps7nO5tV3krPIBh5gmmwh6ClVSsMDClRw=,iv:yed6TLxoI3jmCk9caU0I8SkKiggovJpERs23KC6J2gQ=,tag:CsE6nz/4xORpJojoS3RJXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
